name: Go Build & Format
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:

jobs:
  build:
    name: Build program
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build

    - name: GolangCI-Lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.39  
